/* Shared mock data — pulled from real Forge source so screens feel authentic. */

const ForgeData = {
  project: {
    name: 'sunstone-pickleball',
    path: '~/projects/sunstone-pickleball',
    framework: 'react-vite-tailwind',
    pm: 'pnpm',
    pmVersion: '9.6.0',
    node: '20.11.0',
    branch: 'main',
    ahead: 3,
    behind: 1,
    clean: true,
    stack: ['react 18.3', 'vite 5.4', 'tailwind 3.4', 'react-router 6.26'],
  },

  doctor: {
    summary: { total: 17, high: 3, medium: 8, low: 6, fixed: 4 },
    categories: ['project', 'env', 'deployment', 'react', 'express', 'security'],
    catCounts: { project: 2, env: 1, deployment: 4, react: 5, express: 0, security: 5 },
    issues: [
      { id: 'vercel-spa-rewrite', cat: 'deployment', sev: 'high',
        title: 'Vercel SPA rewrite may be missing',
        file: 'vercel.json',
        rule: 'vercel-spa-rewrite',
        autofix: true,
        note: 'React Router app without rewrite — direct URLs 404 on Vercel.' },
      { id: 'express-cors-all', cat: 'security', sev: 'high',
        title: 'Express CORS may allow all origins',
        file: 'api/index.ts',
        rule: 'express-cors-wildcard',
        autofix: false,
        note: 'cors() called with no options. Restrict to allowed origins.' },
      { id: 'frontend-env-secrets', cat: 'security', sev: 'high',
        title: 'Frontend may reference secret env variables',
        file: 'src/lib/api.ts',
        rule: 'frontend-env-secrets',
        autofix: false,
        note: 'VITE_-prefixed secrets are exposed to the client bundle.' },
      { id: 'missing-env-example', cat: 'env', sev: 'medium',
        title: 'Missing .env.example',
        file: '.env.example',
        rule: 'missing-env-example',
        autofix: true,
        note: 'No example env file. Recipe env-example-baseline can scaffold one.' },
      { id: 'express-helmet', cat: 'express', sev: 'medium',
        title: 'Express app may be missing helmet',
        file: 'api/index.ts',
        rule: 'express-helmet',
        autofix: true,
        note: 'helmet() not installed. Recommended security headers absent.' },
      { id: 'missing-viewport', cat: 'react', sev: 'medium',
        title: 'Missing viewport meta tag',
        file: 'index.html',
        rule: 'index-html-viewport',
        autofix: true,
        note: 'No <meta name="viewport"> — mobile rendering broken.' },
      { id: 'missing-build-script', cat: 'project', sev: 'medium',
        title: 'Missing build script',
        file: 'package.json',
        rule: 'missing-build-script',
        autofix: true,
        note: 'No "build" script. Most CI/CD providers expect one.' },
      { id: 'missing-meta-desc', cat: 'react', sev: 'low',
        title: 'Missing meta description',
        file: 'index.html', rule: 'index-html-meta-description', autofix: true,
        note: 'No meta description — SEO + social link previews affected.' },
      { id: 'missing-og', cat: 'react', sev: 'low',
        title: 'Missing Open Graph metadata',
        file: 'index.html', rule: 'index-html-og', autofix: true,
        note: 'No og:title/og:description — social sharing falls back to URL.' },
      { id: 'missing-lint-script', cat: 'project', sev: 'low',
        title: 'Missing lint script',
        file: 'package.json', rule: 'missing-lint-script', autofix: true,
        note: 'No "lint" script. CI lint enforcement requires one.' },
    ],
  },

  // Diff preview for the currently-selected doctor issue (vercel-spa-rewrite)
  doctorDiff: {
    file: 'vercel.json',
    hunkHeader: '@@ created file ·  vercel.json @@',
    lines: [
      '+{',
      '+  "rewrites": [',
      '+    { "source": "/(.*)", "destination": "/index.html" }',
      '+  ]',
      '+}',
    ],
  },

  // Real recipe slugs from src/templates/recipes/
  recipes: [
    { slug: 'vite-vercel-spa-rewrite',     tags: ['vite','vercel','router'], desc: 'Add vercel.json SPA rewrite for React Router apps', files: 1, op: 'create' },
    { slug: 'supabase-auth-react',         tags: ['supabase','auth','react'], desc: 'Drop-in Supabase auth provider + hook', files: 4, op: 'create' },
    { slug: 'supabase-client-react',       tags: ['supabase','react'], desc: 'Typed Supabase client singleton', files: 2, op: 'create' },
    { slug: 'tailwind-ui-baseline',        tags: ['tailwind','ui'], desc: 'Tailwind base layer, typography, container queries', files: 3, op: 'overwrite' },
    { slug: 'env-example-baseline',        tags: ['env','config'], desc: 'Scaffold .env.example with project-aware keys', files: 1, op: 'create' },
    { slug: 'express-secure-baseline',     tags: ['express','security'], desc: 'helmet + JSON limits + CORS allow-list', files: 1, op: 'append' },
    { slug: 'express-security-baseline',   tags: ['express','security'], desc: 'Stricter variant with rate limiting + cookie flags', files: 1, op: 'append' },
    { slug: 'github-actions-vite',         tags: ['ci','github','vite'], desc: 'CI workflow: install, lint, build', files: 1, op: 'create' },
    { slug: 'github-actions-vite-deploy-check', tags: ['ci','vercel','vite'], desc: 'Wait for Vercel deployment, validate URL', files: 1, op: 'create' },
    { slug: 'playwright-basic-config',     tags: ['testing','e2e'], desc: 'Minimal Playwright config + smoke spec', files: 2, op: 'create' },
    { slug: 'react-router-baseline',       tags: ['react','router'], desc: 'Router shell, routes file, NotFound', files: 3, op: 'create' },
    { slug: 'client-contact-form',         tags: ['react','forms'], desc: 'Validated contact form with toast feedback', files: 2, op: 'create' },
    { slug: 'square-checkout-express',     tags: ['express','payments'], desc: 'Square checkout endpoint scaffold', files: 1, op: 'create' },
    { slug: 'vite-vercel-client-routing',  tags: ['vite','vercel','router'], desc: 'Client routing rewrites + 404 fallback', files: 2, op: 'create' },
  ],

  recipePreview: {
    slug: 'vite-vercel-spa-rewrite',
    desc: 'Adds vercel.json so React Router URLs do not 404 in production.',
    tags: ['vite','vercel','router'],
    notes: [
      'Skips creation if vercel.json already defines a rewrite for /(.*).',
      'Use --force to overwrite existing rewrites.',
      'Safe to run after `forge new ... --template react-vite-tailwind`.',
    ],
    operations: [
      { op: 'create', path: 'vercel.json', bytes: 92 },
    ],
    body: [
      '{',
      '  "rewrites": [',
      '    { "source": "/(.*)", "destination": "/index.html" }',
      '  ]',
      '}',
    ],
  },

  // Recent prompts — built around the real PROMPT_TYPES
  prompts: [
    { id: 'p_8f12', type: 'feature',  mode: 'plan',     task: 'add Supabase auth with Google + email', when: 'today 14:02', tokens: 1842 },
    { id: 'p_8d4a', type: 'debug',    mode: 'implement',task: 'Vercel refresh returns 404 on /events', when: 'today 11:38', tokens: 1106 },
    { id: 'p_8b03', type: 'refactor', mode: 'plan',     task: 'split Hero into HeroLayout + HeroContent', when: 'yesterday', tokens: 924 },
    { id: 'p_8907', type: 'deploy',   mode: 'plan',     task: 'ship pickleball site to Vercel + cutover DNS', when: 'yesterday', tokens: 1456 },
    { id: 'p_87b1', type: 'audit',    mode: 'review',   task: 'check Express API CORS + headers', when: '2 days ago', tokens: 2104 },
    { id: 'p_8633', type: 'test',     mode: 'implement',task: 'add Playwright smoke for /events page',   when: '2 days ago', tokens: 812 },
    { id: 'p_8401', type: 'cleanup',  mode: 'plan',     task: 'remove Stripe references after Square migration', when: '4 days ago', tokens: 1340 },
    { id: 'p_8201', type: 'review',   mode: 'review',   task: 'review auth provider PR #142',          when: '5 days ago', tokens: 1622 },
    { id: 'p_8042', type: 'feature',  mode: 'implement',task: 'events page with calendar grid + filters', when: '6 days ago', tokens: 1980 },
  ],

  // Selected prompt body (excerpt for preview)
  promptBody: [
    '# Feature: add Supabase auth',
    '',
    '## Project context',
    '- stack: react-vite-tailwind',
    '- router: react-router 6.26',
    '- pkg manager: pnpm 9.6.0',
    '',
    '## Task',
    'Add Supabase auth with Google OAuth and email/password.',
    'Persist session across reloads. Gate /admin behind auth.',
    '',
    '## Constraints',
    '- Use the typed client from supabase-client-react.',
    '- Do not expose SUPABASE_SERVICE_ROLE to the client.',
    '- Cover sign-in, sign-up, sign-out, and protected route.',
    '',
    '## Expected deliverables',
    '1. AuthProvider with session sync',
    '2. useAuth() hook',
    '3. <RequireAuth> wrapper for routes',
    '4. SignIn / SignUp pages',
    '5. README block on env vars',
  ],

  // Launch report — current run + previous for diff
  launch: {
    current: { score: 84, when: 'today 11:32', url: 'https://sunstone-pickleball.com', status: 'ready' },
    previous: { score: 78, when: 'yesterday 18:14', url: 'https://sunstone-pickleball.com', status: 'ready' },
    sparkline: [62, 66, 64, 70, 72, 75, 73, 76, 78, 84],
    runs: [
      { id: 'r_4e2', when: 'today 11:32',     score: 84, delta: +6, status: 'ready'   },
      { id: 'r_4d9', when: 'yesterday 18:14', score: 78, delta: +3, status: 'ready'   },
      { id: 'r_4cd', when: '2 days ago 09:02',score: 75, delta: -1, status: 'ready'   },
      { id: 'r_4b1', when: '3 days ago 16:40',score: 76, delta: +6, status: 'ready'   },
      { id: 'r_4a0', when: '4 days ago 11:12',score: 70, delta: 0,  status: 'partial' },
    ],
    checks: [
      // group, name, prev status, current status
      { group: 'Build',      name: 'pnpm install',         prev: 'pass', cur: 'pass'   },
      { group: 'Build',      name: 'typecheck',            prev: 'pass', cur: 'pass'   },
      { group: 'Build',      name: 'build',                prev: 'pass', cur: 'pass'   },
      { group: 'Build',      name: 'bundle size budget',   prev: 'warn', cur: 'pass', change: 'fixed' },
      { group: 'Tests',      name: 'vitest',               prev: 'pass', cur: 'pass'   },
      { group: 'Tests',      name: 'playwright smoke',     prev: 'fail', cur: 'pass', change: 'fixed' },
      { group: 'Deploy',     name: 'vercel.json rewrite',  prev: 'fail', cur: 'pass', change: 'fixed' },
      { group: 'Deploy',     name: 'env vars set',         prev: 'pass', cur: 'pass'   },
      { group: 'Live',       name: 'TLS valid',            prev: 'pass', cur: 'pass'   },
      { group: 'Live',       name: 'homepage 200',         prev: 'pass', cur: 'pass'   },
      { group: 'Live',       name: 'deep link /events',    prev: 'fail', cur: 'pass', change: 'fixed' },
      { group: 'Live',       name: 'lighthouse perf ≥ 80', prev: 'warn', cur: 'warn'   },
      { group: 'Live',       name: 'lighthouse a11y ≥ 90', prev: 'pass', cur: 'warn', change: 'regressed' },
      { group: 'Security',   name: 'no secrets in bundle', prev: 'pass', cur: 'pass'   },
      { group: 'Security',   name: 'CORS allow-list',      prev: 'pass', cur: 'fail', change: 'regressed' },
    ],
  },

  // Forge config — from ~/.forge/config.json
  config: {
    sections: [
      { id: 'general', label: 'General',
        items: [
          { key: 'defaults.packageManager', val: 'pnpm', type: 'enum', options: ['npm','pnpm','yarn','bun'] },
          { key: 'defaults.template',        val: 'react-vite-tailwind', type: 'enum',
            options: ['react-vite','react-vite-tailwind','express-api','client-static-site'] },
          { key: 'defaults.componentPath',   val: 'src/components', type: 'path' },
          { key: 'defaults.openInEditor',    val: true, type: 'bool' },
        ] },
      { id: 'prompts', label: 'Prompts',
        items: [
          { key: 'prompts.defaultMode',  val: 'plan', type: 'enum', options: ['plan','implement','review'] },
          { key: 'prompts.copyToClipboard', val: true, type: 'bool' },
          { key: 'prompts.historyLimit', val: 200, type: 'number' },
        ] },
      { id: 'doctor', label: 'Doctor',
        items: [
          { key: 'doctor.autoFix',       val: false, type: 'bool' },
          { key: 'doctor.skipCategories',val: [], type: 'list',
            options: ['project','env','deployment','react','express','security'] },
          { key: 'doctor.failOn',        val: 'high', type: 'enum', options: ['low','medium','high'] },
        ] },
      { id: 'launch', label: 'Launch',
        items: [
          { key: 'launch.urlTimeoutMs', val: 15000, type: 'number' },
          { key: 'launch.strict',       val: false, type: 'bool' },
          { key: 'launch.budgets.bundleKb', val: 350, type: 'number' },
        ] },
      { id: 'paths', label: 'Paths',
        items: [
          { key: 'paths.forgeHome',   val: '~/.forge', type: 'path', readOnly: true },
          { key: 'paths.recipes',     val: '~/.forge/recipes',   type: 'path', readOnly: true },
          { key: 'paths.templates',   val: '~/.forge/templates', type: 'path', readOnly: true },
          { key: 'paths.history',     val: '~/.forge/history.json', type: 'path', readOnly: true },
        ] },
    ],
    overrides: [
      { template: 'react-vite-tailwind', file: 'tailwind.config.ts', source: 'user' },
      { template: 'react-vite-tailwind', file: 'index.html',         source: 'user' },
      { template: 'express-api',         file: 'tsconfig.json',      source: 'user' },
    ],
  },

  paletteCommands: [
    { id: 'doctor.run',          group: 'Doctor',  label: 'forge doctor',                 hint: 'Run all rules',         shortcut: 'D' },
    { id: 'doctor.fix',          group: 'Doctor',  label: 'forge doctor --fix',           hint: 'Apply auto-fixes',      shortcut: 'shift+D' },
    { id: 'doctor.deployment',   group: 'Doctor',  label: 'forge doctor --category deployment', hint: 'Filter category' },
    { id: 'prompt.feature',      group: 'Prompts', label: 'forge prompt feature …',       hint: 'Feature prompt' },
    { id: 'prompt.debug',        group: 'Prompts', label: 'forge prompt debug …',         hint: 'Debug prompt' },
    { id: 'prompt.history',      group: 'Prompts', label: 'forge prompt history',         hint: 'Browse history',        shortcut: 'P' },
    { id: 'pack.use',            group: 'Recipes', label: 'forge pack use …',             hint: 'Apply a recipe',        shortcut: 'R' },
    { id: 'pack.list',           group: 'Recipes', label: 'forge pack list',              hint: 'Browse recipes' },
    { id: 'launch.run',          group: 'Launch',  label: 'forge launch',                 hint: 'Run launch checklist',  shortcut: 'L' },
    { id: 'launch.compare',      group: 'Launch',  label: 'forge launch --compare',       hint: 'Compare last two runs' },
    { id: 'new.react-vite-tw',   group: 'New',     label: 'forge new … --template react-vite-tailwind', hint: 'Scaffold project' },
    { id: 'component.scaffold',  group: 'New',     label: 'forge component …',            hint: 'Generate component',    shortcut: 'C' },
    { id: 'config.open',         group: 'Settings',label: 'forge config',                 hint: 'Open settings editor' },
    { id: 'template.list',       group: 'Settings',label: 'forge template list',          hint: 'Inspect templates' },
  ],
};

window.ForgeData = ForgeData;
